frontend:
  image:
    repository: nadamankai/learn-room
    tag: frontend
  deployment:
    replicas: 1
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: nadamankai/learn-room
    tag: backend
  deployment:
    replicas: 2
  service:
    type: ClusterIP
    port: 3000

database:
  host: learnroom-db-host
  port: 5432
  name: learnroom
  user: learnroom-user
  password: learnroom-pwd

jwt:
    secret: learnroom-jwt-secret
    salt: learnroom-jwt-salt
