apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "learn-room.fullname" . }}-db-config
data:
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_USER: "{{ .Values.database.user }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
  DB_NAME: "{{ .Values.database.name }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "learn-room.fullname" . }}-jwt-config
data:
  salt: "{{ .Values.jwt.salt }}"
  JWT_SECRET_KEY: "{{ .Values.jwt.secret }}"
