apiVersion: v1
kind: Service
metadata:
  name: {{ include "learn-room.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "learn-room.name" . }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "learn-room.fullname" . }}-backend
spec:
  selector:
      app: {{ include "learn-room.name" . }}-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}
