apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-room
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: learnroom
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/learnroom
    repoURL: 'https://github.com/Dhouib-Mohamed/learnroom-k8s'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: ''
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/Dhouib-Mohamed/learnroom-k8s'
    path: .
    targetRevision: HEAD
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
